import type { Metadata } from "next";
import Header from "../components/Header"
import "./globals.css";

export const metadata: Metadata = {
  title: "Portefolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
